server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: stub-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      acks: all

app:
  topics:
    in: load-topic
    out: reply-topic

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
